python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=cuda:0