python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=malignancy --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=grade --device=0