python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1
python hparam_search.py mtan --worker=8 --mixed_precision --malignancy --subtype --grade --device=1