python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
python hparam_search.py hs --worker=8 --aux_task_set=11 --grade --config=1 --keep_unlabeled
