python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=3 --malignancy
