python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
python hparam_search.py hs --worker=8 --aux_task_set=12 --malignancy
