python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=3
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=4
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=5
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=6
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=7
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=8
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=9
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=10
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --malignancy --subtype --grade --config=1 --aux_task_set=11


