python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=1 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=2 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --malignancy