python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=3 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=4 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=5 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=6 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=7 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=8 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=9 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=10 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
python main.py hs --worker=8 --aux_coeff=0.25 --split_level=4 --in_channels=32 --drop_rate=0.3 --l2=3e-6 --lr=1e-4 --b_size=8 --num_cumu_batch=4 --aux_task_set=11 --subtype
