python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
python hparam_search.py hs --worker=8 --aux_task_set=8 --subtype --config=1
