python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=malignancy --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=subtype --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel
python main.py stan --in_channels=32 --lr=1e-4 --l2=3e-6 --drop_rate=0.3 --config=2 --mixed_precision --task=grade --worker=8 --att_block=channel