python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
python hparam_search.py stl_3d --worker=8 --mixed_precision --task=subtype
