python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
python main.py tag --lr=1e-4 --worker=8 --in_channels=32 --split_level=4 --drop_rate=0.3 --l2=3e-6 --num_epoch=100 --aux_task_set=3 --malignancy --b_size=8 --num_cumu_batch=4
